# tools/load_oui.py

import csv
from pathlib import Path

OUI_PATH = Path(__file__).resolve().parent.parent / "data" / "vendors_oui.csv"
OUTPUT_PATH = Path(__file__).resolve().parent.parent / "classifiers" / "oui_map.py"


def main():
    print(f"[+] Loading OUI data from {OUI_PATH}")

    oui_map: dict[str, str] = {}

    with open(OUI_PATH, "r", encoding="utf-8", errors="ignore") as f:
        reader = csv.reader(f)
        for row in reader:
            if len(row) < 2:
                continue
            oui = row[0].strip().upper()
            vendor = row[1].strip()
            if not oui or not vendor:
                continue
            oui_map[oui] = vendor

    print(f"[+] Loaded {len(oui_map)} OUI entries")

    # Write a Python file that your classifier can import directly
    with open(OUTPUT_PATH, "w", encoding="utf-8") as f:
        f.write("# Auto-generated by tools/load_oui.py\n")
        f.write("OUI_VENDOR_MAP = {\n")
        for oui, vendor in sorted(oui_map.items()):
            safe_vendor = vendor.replace('"', '\\"')
            f.write(f'    "{oui}": "{safe_vendor}",\n')
        f.write("}\n")

    print(f"[+] Wrote vendor map to {OUTPUT_PATH}")


if __name__ == "__main__":
    main()
